# short class ID (human readable)
class = "CSCI 2390"
# list email addresses whose API keys get admin access
admins = ["tester@admin.edu"]
# list email addresses who should receive notification emails
staff = ["tester@admin.edu"]
# custom template directory
template_dir = "templates"
# custom resource directory (e.g., for images, CSS, JS)
resource_dir = "resources"
# a secret that will be hashed into user's API keys to make them unforgeable
secret = "SECRET"
# whether to send emails (set to false for development)
send_emails = true
# whether to run w/edna
is_baseline = false
mysql_user = "tester"
mysql_pass = "pass"
